spring.application.name=Boilerplate

# (dev, staging, production)
spring.profiles.active=dev

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000

file.upload-dir=../PUBLIC_FILE
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:postgresql://localhost:5432/BCL001
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configurations
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Enable all Actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=shutdown

# Customize health endpoint details
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Enable detailed info for specific health checks
management.health.db.enabled=true
management.health.diskspace.enabled=true
management.health.ping.enabled=true

# Configure metrics
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=battery-control-line

# Application info (customized)
info.app.name=Battery Control Line
info.app.description=Monitoring for Battery Control Line
info.app.version=1.0.0
info.app.environment=production

# Logging levels
management.endpoint.logfile.enabled=true
management.endpoint.logfile.external-file=/var/log/battery-control-line/application.log
logging.file.path=/var/log/battery-control-line
logging.level.org.springframework=INFO
logging.level.com.yourcompany=DEBUG

# Thread dump endpoint
management.endpoint.threaddump.enabled=true
management.endpoint.heapdump.enabled=true


